# PRIMITIVE TYPE NAMES
INT_NAME = 'int'
STRING_NAME = 'str'
FLOAT_NAME = 'float'
BOOL_NAME = 'bool'

# PRIMITIVE TYPE SIZES OF STRUCT PACK
DOUBLE_SIZE = 8
INT_SIZE = 8
CHAR_SIZE = 1
BOOL_SIZE = 1

# STRING SIZE VARIABLE NAME ENDS WITH:
END_OF_STRING_SIZE_VARIABLE = '_size'

# EMPTY BINARY, NOTHING READ
EMPTY_BINARY = b''
